### ISSUE TITLE
Certificate verification not working on xubuntu 14.04 + Python 3.4.3

### ISSUE THREAD

**Issue by Arek75** [nwestfal/pylotro#6]
I don't know what's causing this, but even after chasing down the certificate chain and rebuilding the certfile, Python 3.4.3 on xubuntu 14.04 won't verify the certificate chain for me.  If I stick a "raise" after the E15 error is set, it tells me that SSL Verification failed.  I think the cause is that the certificate chain is effectively self-signed.  I'd fix it myself, but my experience with this is roughly zero.  I think the problem may be in ubuntu somewhere, and not in Python or PyLotRO, but given how popular the *buntu distros are, I'd like to see if this can be fixed in PyLotRO without disabling certificate verification.

**Comment by srukle** [comment]
I'm getting SSL errors on Mac, Windows, and Linux OS -- not just PyLotRO. I'm unsure what the problem is. I contacted LOTRO on Twitter, and support says it's not their end.

**Comment by nwestfal** [comment]
I'm using Python 3.4.1 on OpenSUSE 13.1 and not seeing any SSL errors connecting to LOTRO.

**Comment by Arek75** [comment]
Ok, I think I've figured this out...I used xubuntu 14.04 LTS to test.  Did a bit of poking around and found this:  http://packages.ubuntu.com/trusty/gnutls-bin - note the version: 3.0.11+really2.12.23-12ubuntu2.4.  That looks to me like they've "hybridized" gnutls on 14.04 for the sake of "compatibility".  Bleh.  Closing with this comment - I'll make sure and note that the native version won't work on 14.04 unless you use Python 2.7 (the default).  I should be able to release a windows build for those people (and actual windows users) in a couple of days, tho. :)

Note:  I haven't tested with newer versions of ubuntu yet (I wanted to test on LTS first), so a test from someone running one of those would be very welcome, but since they actual 3.x versions of gnutls, like OpenSUSE does, and not a hybrid 3.x+2.x version, I don't expect them to break.

**Comment by Arek75** [comment]
Not completely figured out yet....I'll definitely want to test on a newer xubuntu.  It seems that the way python handles SSL changed in 3.4.3+, and that this change may be what's causing the problem.  If this is the case, fixing it without breaking <= Python 3.4 will be non-trivial.  Leaving closed until I can confirm this is the problem.
