### ISSUE TITLE
Some errors in the output

### ISSUE THREAD

**Issue by Kingsy** [nwestfal/pylotro#9]
Hi,

So the game is working just great however the store and help pages in the game are blank.
If you choose to use an external browser the game crashes. When you use in game browser the store and help pages are a black screen.

I have installed firefox via winetricks in the hopes the game would use this but with no avail.
However I did notice there are some errors in the pylotro output which are as follows.

0009:err:winediag:MIDIMAP_drvOpen No software synthesizer midi port found, Midi sound output probably won't work.

[1013/215805.977:ERROR:network_change_notifier_win.cc(156)] WSALookupServiceBegin failed with: 8

[1013/215948.145:ERROR:child_process_launcher.cc(522)] Failed to launch child process

[1013/220042.809:ERROR:child_process_launcher.cc(522)] Failed to launch child process

*** Finished ***

Do you think these errors are related to the black screen?

Can you recommend something to fix the errors and potentially get the ingame store working?

Thanks

Chris

**Comment by nwestfal** [comment]
Hi, I believe it is a known issue that the in-game browser does not work, so you have to use the external browser.  Make sure that the game client you are using is the "lotroclient_awesomium.exe" - see the "Additional Comments" section here:

https://appdb.winehq.org/objectManager.php?sClass=version&iId=36477

NOTE: You should only need to download (or modify existing one per the note) the TurbineLauncher.exe.config file as I believe the lotroclient_awesomium.exe is now automatically downloaded whenever you patch the game.  The pylotro output will show if it is using lotroclient.exe or lotroclient_awesomium.exe.

If you still have problems also see some of the user comments at the above link also, there may be something there that can help you.  For what it is worth, I hadn't played the game in awhile, but I patched it up with the latest updates and launched the game and tried the store, and it came up fine in the external browser.  I didn't need install Firefox via winetricks or anything like that, it just launches in the Firefox packaged with OpenSUSE.

**Comment by Kingsy** [comment]
hm, well I have lotroclient_awesomium.exe, however I cant seem to swtich the launcher for pylotro.

The TurbineLauncher.exe.config only contains

<?xml version="1.0" encoding="utf-8" ?>
<configuration>
	<system.windows.forms jitDebugging="true" />
	<startup>
		<requiredRuntime version="V1.1.4322" safemode="true"/>
		<supportedRuntime version="V1.1.4322" />
	</startup>
	<appSettings>
		<add key="Launcher.DataCenterService.GLS" value="http://moria.gls.lotro.com/GLS.DataCenterServer/Service.asmx"/>

		<add key="DataCenter.GameName" value="LOTRO" />
		<add key="DataCenter.DefaultCenter" value="LOTRO" />
		<add key="Product.DocumentFolder" value="The Lord of the Rings Online"/>
		<add key="Launcher.DocumentFolder" value="Launcher"/>
	</appSettings>
  <system.net>
    <settings>
      <servicePointManager expect100Continue="false" />
    </settings>
  </system.net>
</configuration>

**Comment by nwestfal** [comment]
Make sure the game or launcher isn't running when you edit it.  This is what mine looks like:

```
<?xml version="1.0" encoding="utf-8" ?>
<configuration>
        <system.windows.forms jitDebugging="true" />
        <startup>
                <requiredRuntime version="V1.1.4322" safemode="true"/>
                <supportedRuntime version="V1.1.4322" />
        </startup>
        <appSettings>
                <add key="Launcher.DataCenterService.GLS" value="http://moria.gls.lotro.com/GLS.DataCenterServer/Service.asmx"/>

                <add key="DataCenter.GameName" value="LOTRO" />
                <add key="DataCenter.DefaultCenter" value="LOTRO" />
                <add key="Product.DocumentFolder" value="The Lord of the Rings Online"/>
                <add key="Launcher.DocumentFolder" value="Launcher"/>

    <add authoritative="true" key="GameClient.WIN32.Filename" value="lotroclient_awesomium.exe" />

        </appSettings>
  <system.net>
    <settings>
      <servicePointManager expect100Continue="false" />
    </settings>
  </system.net>
</configuration>
```

**Comment by nwestfal** [comment]
Oh don't change it in launcher.config, just add that one line in TurbineLauncher.exe.config and pylotro will find it and override the default value in launcher.config.

**Comment by Kingsy** [comment]
got it, i didnt have that line but I added it manually from your paste and now it works!!
Still have a problem with lotro crashing after it opens the firefox window though. I asks me if I want to open the store as an external browser then when I click yes, the window opens. After I close the firefox window lotro is unresponsive and I have to crash out.
Seen this before?

**Comment by nwestfal** [comment]
Hmmm no not really.  But I will try mine again after my game is done patching.  It might be something with the wine version or something.  I haven't updated my wine in awhile.  I'm on 3.4.

Anyway, the reason the launcher.config reverts after you edit it is because pylotro downloads that file every time from the lotro servers.  So pylotro just checks the TurbineLauncher.exe.config for the override value and uses it instead if it finds it there.  That's the best way to do it since that's the file that SSG uses to override it with their own launcher.

**Comment by Kingsy** [comment]
wow I am on wine-3.0 (Ubuntu 3.0-1ubuntu1) so perhaps I could do with an upgrade.
Let me know if yours works.

**Comment by Kingsy** [comment]
It still doesnt work even with 3.18 so it must be my window manager.
I am using dwm a tiling window manager so its a bit unusual, so I will look into that.
Anyway thankyou for all your help
